[package]
name = "jacks_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
jacks_sports_zone_api = {path="../jacks_sports_zone_api"}
flexi_logger = "0.30.1"
log = "0.4.27"
serde_json = "1.0.140"
